# Generated by Django 2.2.9 on 2020-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to='icons')),
                ('video_file', models.FileField(upload_to='videos')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
