# Generated by Django 2.2.9 on 2020-10-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0002_upload_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_file',
            new_name='UploadFile',
        ),
    ]
