# Generated by Django 2.2.9 on 2020-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0003_auto_20201002_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos')),
                ('ctreate_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
