# Generated by Django 2.2.9 on 2020-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0004_tofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=500)),
                ('video_name2', models.CharField(max_length=50, verbose_name='视频别名')),
                ('file_path', models.CharField(max_length=100, verbose_name='视频存储路径')),
                ('task_id', models.CharField(max_length=50, verbose_name='异步剪裁ID')),
                ('status', models.IntegerField(verbose_name='视频剪裁状态')),
                ('result', models.CharField(max_length=500, verbose_name='异步剪裁结果')),
                ('runtime', models.FloatField(max_length=10, verbose_name='异步任务运行时间')),
                ('traceback', models.CharField(max_length=1000, verbose_name='报错')),
                ('children', models.CharField(max_length=500, verbose_name='字段保留')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='存储时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'videostatus',
            },
        ),
        migrations.AlterModelTable(
            name='tofiles',
            table='tofiles',
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='uploadfiles',
        ),
    ]
