# Generated by Django 2.2.9 on 2020-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0005_auto_20201003_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostatus',
            name='file_path2',
            field=models.CharField(max_length=100, null=True, verbose_name='视频剪裁后路径'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='children',
            field=models.CharField(max_length=500, null=True, verbose_name='字段保留'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='result',
            field=models.CharField(max_length=500, null=True, verbose_name='异步剪裁结果'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='视频剪裁状态'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='task_id',
            field=models.CharField(max_length=50, null=True, verbose_name='异步剪裁ID'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='traceback',
            field=models.CharField(max_length=1000, null=True, verbose_name='报错'),
        ),
        migrations.AlterField(
            model_name='videostatus',
            name='video_name2',
            field=models.CharField(max_length=50, null=True, verbose_name='视频别名'),
        ),
    ]
