# Generated by Django 2.2.9 on 2020-10-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipping', '0006_auto_20201003_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostatus',
            name='runtime',
            field=models.FloatField(max_length=10, null=True, verbose_name='异步任务运行时间'),
        ),
    ]
